-- MySQL Script generated by MySQL Workbench
-- Thu Dec 27 08:20:06 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Coupon_DB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Coupon_DB` ;

-- -----------------------------------------------------
-- Schema Coupon_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Coupon_DB` DEFAULT CHARACTER SET utf8 ;
USE `Coupon_DB` ;

-- -----------------------------------------------------
-- Table `Coupon_DB`.`CP_Tb_Companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Coupon_DB`.`CP_Tb_Companies` ;

CREATE TABLE IF NOT EXISTS `Coupon_DB`.`CP_Tb_Companies` (
  `Companie_Id` INT NOT NULL AUTO_INCREMENT,
  `Companie_Name` VARCHAR(45) NOT NULL COMMENT 'The name of the company that provides coupons',
  `Companie_Email` VARCHAR(318) NOT NULL COMMENT 'The email address is divided into 2 parts separated by \"@\" character.\nlocal-part@domain.\nlocal-part ==> until 64 characters\ndomain    ==> until 255 characters\nsee wikipedia \"Email address\"',
  `Companie_Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Companie_Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Coupon_DB`.`CP_Tb_Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Coupon_DB`.`CP_Tb_Customers` ;

CREATE TABLE IF NOT EXISTS `Coupon_DB`.`CP_Tb_Customers` (
  `Customer_Id` INT NOT NULL AUTO_INCREMENT,
  `Customer_First_Name` VARCHAR(45) NOT NULL,
  `Customer_Last_Name` VARCHAR(45) NOT NULL,
  `Customer_Email` VARCHAR(318) NOT NULL COMMENT 'The email address is divided into 2 parts separated by \"@\" character.\nlocal-part@domain.\nlocal-part ==> until 64 characters\ndomain    ==> until 255 characters\nsee wikipedia \"Email address\"',
  `Customer_Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Customer_Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Coupon_DB`.`CP_Tb_Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Coupon_DB`.`CP_Tb_Categories` ;

CREATE TABLE IF NOT EXISTS `Coupon_DB`.`CP_Tb_Categories` (
  `Category_Id` INT NOT NULL AUTO_INCREMENT,
  `Category_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Category_Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Coupon_DB`.`CP_Tb_Coupons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Coupon_DB`.`CP_Tb_Coupons` ;

CREATE TABLE IF NOT EXISTS `Coupon_DB`.`CP_Tb_Coupons` (
  `Coupon_Id` INT NULL AUTO_INCREMENT,
  `Coupon_Company_Id` INT NOT NULL,
  `Copuon_Category_Id` INT NOT NULL,
  `Coupon_Title` VARCHAR(100) NOT NULL COMMENT 'Short description of the coupon',
  `Coupon_Description` VARCHAR(400) NOT NULL COMMENT 'Long description of the coupon ',
  `Coupon_Start_Date` DATETIME NULL COMMENT 'Coupon creation Date',
  `Coupon_End_Date` DATETIME NULL COMMENT 'Coupon expiration date',
  `Coupon_Amount` INT NULL COMMENT 'Quantity of coupons in stock',
  `Coupon_Price` DECIMAL NULL COMMENT 'Coupon price',
  `Coupon_Image` VARCHAR(250) NULL COMMENT 'File address for the coupon image',
  `Coupon_Inserted_Date` DATETIME NOT NULL,
  `Coupon_Modified_date` DATETIME NOT NULL,
  PRIMARY KEY (`Coupon_Id`),
  CONSTRAINT `fk_CP_Tb_Coupons_CP_Tb_Companies1`
    FOREIGN KEY (`Coupon_Company_Id`)
    REFERENCES `Coupon_DB`.`CP_Tb_Companies` (`Companie_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CP_Tb_Coupons_CP_Tb_Categories1`
    FOREIGN KEY (`Copuon_Category_Id`)
    REFERENCES `Coupon_DB`.`CP_Tb_Categories` (`Category_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_CP_Tb_Coupons_CP_Tb_Companies1_idx` ON `Coupon_DB`.`CP_Tb_Coupons` (`Coupon_Company_Id` ASC) ;

CREATE INDEX `fk_CP_Tb_Coupons_CP_Tb_Categories1_idx` ON `Coupon_DB`.`CP_Tb_Coupons` (`Copuon_Category_Id` ASC);


-- -----------------------------------------------------
-- Table `Coupon_DB`.`CP_Tb_Customers_VS_Coupons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Coupon_DB`.`CP_Tb_Customers_VS_Coupons` ;

CREATE TABLE IF NOT EXISTS `Coupon_DB`.`CP_Tb_Customers_VS_Coupons` (
  `Coupon_Id` INT NOT NULL,
  `Customer_id` INT NOT NULL,
  PRIMARY KEY (`Coupon_Id`, `Customer_id`),
  CONSTRAINT `fk_CP_Tb_Customers_VS_Coupons_CP_Tb_Coupons1`
    FOREIGN KEY (`Coupon_Id`)
    REFERENCES `Coupon_DB`.`CP_Tb_Coupons` (`Coupon_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CP_Tb_Customers_VS_Coupons_CP_Tb_Customers1`
    FOREIGN KEY (`Customer_id`)
    REFERENCES `Coupon_DB`.`CP_Tb_Customers` (`Customer_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CP_Tb_Customers_VS_Coupons_CP_Tb_Customers1_idx` ON `Coupon_DB`.`CP_Tb_Customers_VS_Coupons` (`Customer_id` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
